spring.application.name=protospace-c

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/protospace_c_db
spring.datasource.username=roll
spring.datasource.password=${POSTGRESQL_PASSWORD}
spring.flyway.baselineOnMigrate=true